version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: mysql-monsters
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: hunter_notes
      MYSQL_USER: hunter_user
      MYSQL_PASSWORD: hunterpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:
